CLASS zcl_03_17_record_mb DEFINITION
  PUBLIC
  INHERITING FROM zcl_03_17_construction_mb
  FINAL CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_03_17_record_mb IMPLEMENTATION.
ENDCLASS.
