CLASS zcl_02_lion_mb DEFINITION INHERITING FROM zcl_02_animal_mb
  PUBLIC
  CREATE PUBLIC .
  PUBLIC SECTION.
    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_02_lion_mb IMPLEMENTATION.
  METHOD walk.
    rv_walk = 'The lion walks'.
  ENDMETHOD.
ENDCLASS.
