CLASS zcl_02_hija_mb DEFINITION INHERITING FROM zcl_02_padre_mb "Citamos de quien hereda
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_02_hija_mb IMPLEMENTATION.
ENDCLASS.
