CLASS zcl_03_15_keyboard_mb DEFINITION
  PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    DATA: keyboard_type TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_03_15_keyboard_mb IMPLEMENTATION.
ENDCLASS.
