CLASS zcl_03_16_vat_indicator_mb DEFINITION
  PUBLIC   FINAL   CREATE PUBLIC.

  PUBLIC SECTION.
    DATA vat_ind TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_03_16_vat_indicator_mb IMPLEMENTATION.
ENDCLASS.
