CLASS zcl_03_11_b_test_mb DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA  atr_a TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_03_11_b_test_mb IMPLEMENTATION.
ENDCLASS.
