CLASS zcl_02_hija2_mb DEFINITION INHERITING FROM zcl_02_hija_mb
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_02_hija2_mb IMPLEMENTATION.
ENDCLASS.
